- id: '1675797444753'
  alias: Great Room Side Shade Closed
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '-1:00'
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.closed_2
    metadata: {}
  mode: single
- id: '1675798534763'
  alias: Close All Blinds
  description: '30 min after sunset closes all blinds '
  trigger:
  - platform: sun
    event: sunset
    offset: 00:30:00
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.close_blinds
    metadata: {}
  - service: scene.turn_on
    target:
      entity_id: scene.close_blinds_bedroom
    metadata: {}
  mode: single
- id: '1682987519193'
  alias: Dusty Charging Check
  description: ''
  trigger:
  - platform: time
    at: '19:06:00'
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: vacuum.dusty_jr
      attribute: status
      for:
        hours: 0
        minutes: 0
        seconds: 5
      state: Charging
  action:
  - service: script.send_dusty_home
    data: {}
  mode: single
- id: '1682989182859'
  alias: Cleanopatra Charging Check
  description: ''
  trigger:
  - platform: time
    at: '19:05:00'
  condition:
  - condition: not
    conditions:
    - condition: state
      for:
        hours: 0
        minutes: 0
        seconds: 5
      state: Charging
      entity_id: vacuum.cleanopatra
      attribute: status
  action:
  - service: script.send_cleanopatra_home_dialog
    data: {}
  mode: single
- id: '1683654242030'
  alias: Pico First Floor Light Entity Control
  description: ''
  use_blueprint:
    path: smartqasa/lutron_pico_5_light.yaml
    input:
      pico_1: ae2cfeda57affa50c0e00e2e8320396e
      entity:
      - light.first_floor_lights
      step: 5
      transition_on: 3
      transition_off: 3
- id: '1683820642231'
  alias: Blinds - Great Room Open
  description: Opens great room blinds 30 min after sunrise
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.open_blinds_great_room
    metadata: {}
  mode: single
- id: '1683820819229'
  alias: Open Back Blinds Partial
  description: Opens back blinds slightly an hour before sunrise
  trigger:
  - platform: sun
    event: sunrise
    offset: '-1800'
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.open_back_blinds_partial
    metadata: {}
  mode: single
- id: '1684062099631'
  alias: Blinds - Bedroom Open
  description: 9am
  trigger:
  - platform: time
    at: 07:30:00
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.open_blinds_bedroom
    metadata: {}
  mode: single
- id: '1684067381055'
  alias: Blinds - Bedroom Partial
  description: 7am
  trigger:
  - platform: time
    at: 07:00:00
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.blinds_bedroom_partial
    metadata: {}
  mode: single
- id: '1704823288280'
  alias: Kitchen Light Fade
  description: ''
  trigger:
  - platform: time
    at: '18:30:00'
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  action:
  - service: script.light_fader
    data:
      lampBrightnessScale: zeroToTwoFiftyFive
      easingTypeInput: easeInOutCubic
      endBrightnessPercent: 5
      endBrightnessEntityScale: zeroToOneHundred
      autoCancelThreshold: 10
      shouldStopIfTheLampIsTurnedOffDuringTheFade: true
      shouldResetTheStopEntityToOffAtStart: false
      shouldInvertTheValueOfTheStopEntity: false
      minimumStepDelayInMilliseconds: 100
      shouldTryToUseNativeLampTransitionsToo: false
      isDebugMode: false
      light: light.kitchen
      transitionTime:
        hours: 0
        minutes: 30
        seconds: 0
  mode: single
- id: '1704824306232'
  alias: Great Room Light Fade
  description: ''
  trigger:
  - platform: time
    at: '18:30:00'
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  action:
  - service: script.light_fader
    data:
      lampBrightnessScale: zeroToTwoFiftyFive
      easingTypeInput: easeInOutCubic
      endBrightnessPercent: 5
      endBrightnessEntityScale: zeroToOneHundred
      autoCancelThreshold: 10
      shouldStopIfTheLampIsTurnedOffDuringTheFade: true
      shouldResetTheStopEntityToOffAtStart: false
      shouldInvertTheValueOfTheStopEntity: false
      minimumStepDelayInMilliseconds: 100
      shouldTryToUseNativeLampTransitionsToo: false
      isDebugMode: false
      light: light.great_room
      transitionTime:
        hours: 0
        minutes: 30
        seconds: 0
  mode: single
- id: '1704824348868'
  alias: Mudroom Light Fade
  description: ''
  trigger:
  - platform: time
    at: '18:30:00'
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  action:
  - service: script.light_fader
    data:
      lampBrightnessScale: zeroToTwoFiftyFive
      easingTypeInput: easeInOutCubic
      endBrightnessPercent: 5
      endBrightnessEntityScale: zeroToOneHundred
      autoCancelThreshold: 10
      shouldStopIfTheLampIsTurnedOffDuringTheFade: true
      shouldResetTheStopEntityToOffAtStart: false
      shouldInvertTheValueOfTheStopEntity: false
      minimumStepDelayInMilliseconds: 100
      shouldTryToUseNativeLampTransitionsToo: false
      isDebugMode: false
      light: light.mudroom
      transitionTime:
        hours: 0
        minutes: 30
        seconds: 0
  mode: single
- id: '1704824381231'
  alias: Foyer Offices Light Fade
  description: ''
  trigger:
  - platform: time
    at: '18:30:00'
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  action:
  - service: script.light_fader
    data:
      lampBrightnessScale: zeroToTwoFiftyFive
      easingTypeInput: easeInOutCubic
      endBrightnessPercent: 5
      endBrightnessEntityScale: zeroToOneHundred
      autoCancelThreshold: 10
      shouldStopIfTheLampIsTurnedOffDuringTheFade: true
      shouldResetTheStopEntityToOffAtStart: false
      shouldInvertTheValueOfTheStopEntity: false
      minimumStepDelayInMilliseconds: 100
      shouldTryToUseNativeLampTransitionsToo: false
      isDebugMode: false
      light: light.offices
      transitionTime:
        hours: 0
        minutes: 30
        seconds: 0
  mode: single
- id: '1704824454444'
  alias: Solarium Light Fade
  description: ''
  trigger:
  - platform: time
    at: '18:30:00'
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  action:
  - service: script.light_fader
    data:
      lampBrightnessScale: zeroToTwoFiftyFive
      easingTypeInput: easeInOutCubic
      endBrightnessPercent: 5
      endBrightnessEntityScale: zeroToOneHundred
      autoCancelThreshold: 10
      shouldStopIfTheLampIsTurnedOffDuringTheFade: true
      shouldResetTheStopEntityToOffAtStart: false
      shouldInvertTheValueOfTheStopEntity: false
      minimumStepDelayInMilliseconds: 60000
      shouldTryToUseNativeLampTransitionsToo: false
      isDebugMode: false
      light: light.solarium
      transitionTime:
        hours: 0
        minutes: 30
        seconds: 0
  mode: single
- id: '1704824493298'
  alias: Basement Light Fade
  description: ''
  trigger:
  - platform: time
    at: '18:30:00'
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  action:
  - service: script.light_fader
    data:
      lampBrightnessScale: zeroToTwoFiftyFive
      easingTypeInput: easeInOutCubic
      endBrightnessPercent: 5
      endBrightnessEntityScale: zeroToOneHundred
      autoCancelThreshold: 10
      shouldStopIfTheLampIsTurnedOffDuringTheFade: true
      shouldResetTheStopEntityToOffAtStart: false
      shouldInvertTheValueOfTheStopEntity: false
      minimumStepDelayInMilliseconds: 100
      shouldTryToUseNativeLampTransitionsToo: false
      isDebugMode: false
      light: light.basement
      transitionTime:
        hours: 0
        minutes: 30
        seconds: 0
  mode: single
- id: '1704827475326'
  alias: Dusk Kitchen Lights On
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:45:00
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  - condition: state
    entity_id: light.kitchen
    state: 'off'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 2
    target:
      entity_id:
      - light.kitchen
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 45
      transition: 300
    target:
      entity_id: light.kitchen
  mode: single
- id: '1704828190029'
  alias: Dusk Great Room Lights On
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:45:00
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  - condition: state
    entity_id: light.great_room
    state: 'off'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 1
    target:
      entity_id:
      - light.great_room
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 45
      transition: 300
    target:
      entity_id: light.great_room
  mode: single
- id: '1704828220306'
  alias: Dusk Mudroom Lights On
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:45:00
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  - condition: state
    entity_id: light.mudroom
    state: 'off'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 1
    target:
      entity_id:
      - light.mudroom
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 45
      transition: 300
    target:
      entity_id: light.mudroom
  mode: single
- id: '1704828256062'
  alias: Dusk Foyer Offices Lights On
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:45:00
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  - condition: state
    entity_id: light.offices
    state: 'off'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 1
    target:
      entity_id:
      - light.offices
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 45
      transition: 300
    target:
      entity_id: light.offices
  mode: single
- id: '1704828323384'
  alias: Dusk Solarium Lights On
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:45:00
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  - condition: state
    entity_id: light.solarium
    state: 'off'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 1
    target:
      entity_id:
      - light.solarium
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 45
      transition: 300
    target:
      entity_id: light.solarium
  mode: single
- id: '1704828349964'
  alias: Dusk Basement Lights On
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:45:00
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  - condition: state
    entity_id: light.basement
    state: 'off'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 1
    target:
      entity_id:
      - light.basement
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 45
      transition: 300
    target:
      entity_id: light.basement
  mode: single
